module.exports = {
  CONNECTED: 'CHAT_SERVER_CONNECTED',
  INITIALIZE_USER: 'CHAT_SERVER_INITIALIZE_USER',
  INITIALIZATION_COMPLETED: 'CHAT_SERVER_INITIALIZATION_COMPLETED',
  NEW_MESSAGE: 'CHAT_SERVER_NEW_MESSAGE',
  USER_DISCONNETED: 'CHAT_SERVER_USER_DISCONNECTED',
  GET_USERS: 'CHAT_SERVER_GET_USERS'
}
